#!/bin/sh

## Idea taken from the folks at Thoughtbot with their thoughtbot/laptop project
## Thanks!

## Allister Antosik

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
chsh -s "$(which zsh)"

# Powerline Fonts
git clone https://github.com/powerline/fonts.git
./fonts/install.sh
rm -rf fonts

# Git config
cp -rf dotfiles/gitconfig.local ~/.gitconfig
cp -rf dotfiles/gitignore.local ~/.gitignore
cp -rf dotfiles/gitmessage.local ~/.gitmessage

# Vim
rm -rf ~/.vim/bundle/Vundle.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

cp -rf dotfiles/vimrc.local ~/.vimrc
vim +PluginInstall +qall

# Tmux
cp -rf dotfiles/tmux.conf.local ~/.tmux.conf

# zshrc
cp -rf dotfiles/zshrc.local ~/.zshrc

# Install Peco for ZSH
rm -rf ~/.oh-my-zsh/custom/plugins/zsh-peco-history
git clone https://github.com/jimeh/zsh-peco-history.git ~/.oh-my-zsh/custom/plugins/zsh-peco-history

echo "DONE!"
