#!/bin/sh

## Idea taken from the folks at Thoughtbot with their thoughtbot/laptop project
## Thanks!

## Allister Antosik

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
chsh -s "$(which zsh)"

# Homebrew

## Install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

## Update Homebrew
brew update

## Install brews
brew install git
brew install vim
brew install tmux
brew install lnav
brew install peco
brew install prettyping
brew install diff-so-fancy
brew install zsh-autosuggestions

# Powerline Fonts
git clone https://github.com/powerline/fonts.git
./fonts/install.sh
rm -rf fonts

# Git config
cp -rf dotfiles/gitconfig.local ~/.gitconfig
cp -rf dotfiles/gitignore.local ~/.gitignore
cp -rf dotfiles/gitmessage.local ~/.gitmessage
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
git config --global color.ui true
git config --global color.diff-highlight.oldNormal    "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal    "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"
git config --global color.diff.meta       "yellow"
git config --global color.diff.frag       "magenta bold"
git config --global color.diff.commit     "yellow bold"
git config --global color.diff.old        "red bold"
git config --global color.diff.new        "green bold"
git config --global color.diff.whitespace "red reverse"

# Vim
rm -rf ~/.vim/bundle/Vundle.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

cp -rf dotfiles/vimrc.local ~/.vimrc
vim +PluginInstall +qall

# Tmux
cp -rf dotfiles/tmux.conf.local ~/.tmux.conf

# zshrc
cp -rf dotfiles/zshrc.local ~/.zshrc

# Install Peco for ZSH
rm -rf ~/.oh-my-zsh/custom/plugins/zsh-peco-history
git clone https://github.com/jimeh/zsh-peco-history.git ~/.oh-my-zsh/custom/plugins/zsh-peco-history

# If Apps to be installed
if [ -n "$1" ]; then
  brew tap caskroom/cask

  brew cask install google-chrome
  brew cask install iterm2
  brew cask install spotify
  brew cask install 1password
fi


echo "DONE!"

